### PR TITLE
Russian localization fix

### PR DESCRIPTION
**Pull request by Blueberryy**
Fixed machine translation text.

(Used official tf2 localization file and some wiki websites)

### CODE REVIEW

**Comment by Kataiser** [comment]
Yo awesome! Now we have two Russian contributors. Also worth noting that I plan on removing all or most localization of community gamemodes (as per #195) but I haven't gotten around to it.

**Comment by Kataiser** [comment]
Oh right the test fails cause you can't actually change stuff in English.json. Will fix, Smissmas is a good call

**Comment by Kataiser** [comment]
I see you've credited yourself as berry in the file, would you prefer for me to use berry or Blueberryy in the changelog?

**Comment by Blueberryy** [comment]
> I see you've credited yourself as berry in the file, would you prefer for me to use berry or Blueberryy in the changelog?

Ah, berry is my steam name but okay i will do that soon

**Comment by Kataiser** [comment]
By changelog I mean the release patch notes btw, idk if that was clear

**Comment by Blueberryy** [comment]
Ah i planned to change back custom gamemode names to their original English versions

**Comment by Kataiser** [comment]
Don't worry about it, I'll do it from the code side and remove them from all languages

**Pull request merged**
